import { FormEvent, useState } from "react";
import { ConfirmDialog } from "../../components/common/ConfirmDialog";
import type { Booking, PaymentMethod, Resident } from "../../types/api";
import { formatCurrencyMinor } from "../../utils/format";
import { parseMoneyToMinorUnits } from "../../utils/money";
import { methodLabel, paymentMethods, residentName } from "./paymentView";

export function CreatePaymentDialog({ open, bookings, residentsById, saving, error, onCreate, onClose }: { open: boolean; bookings: Booking[]; residentsById: Map<number, Resident>; saving: boolean; error: string | null; onCreate: (input: { bookingId: number; residentId: number; amountMinor: number; currency?: string; method: PaymentMethod; paidAt?: string; notes?: string }) => void; onClose: () => void }) {
  const [bookingId, setBookingId] = useState("");
  const [amount, setAmount] = useState("");
  const [method, setMethod] = useState<PaymentMethod>("cash");
  const [paidAt, setPaidAt] = useState("");
  const [notes, setNotes] = useState("");
  const [localError, setLocalError] = useState<string | null>(null);
  const selected = bookings.find((booking) => booking.id === Number(bookingId));
  function submit(event: FormEvent) {
    event.preventDefault();
    setLocalError(null);
    try {
      if (!selected) throw new Error("Booking is required.");
      const amountMinor = parseMoneyToMinorUnits(amount);
      onCreate({ bookingId: selected.id, residentId: selected.resident_id, amountMinor, currency: selected.currency, method, paidAt: paidAt || undefined, notes: notes.trim() || undefined });
    } catch (err) {
      setLocalError(err instanceof Error ? err.message : "Invalid payment.");
    }
  }
  return (
    <ConfirmDialog open={open} title="Add Payment" description="Payment references are generated by the backend. Multiple part-payments for the same booking remain separate records." onClose={onClose}>
      <form onSubmit={submit} className="space-y-4">
        <label className="block text-sm font-medium">Booking<select aria-label="Payment booking" value={bookingId} onChange={(event) => setBookingId(event.target.value)} className="mt-1 w-full rounded-md border border-border px-3 py-2"><option value="">Select booking</option>{bookings.map((booking) => <option key={booking.id} value={booking.id}>{booking.booking_number} - {residentName(residentsById.get(booking.resident_id))} - {formatCurrencyMinor(booking.total_amount_minor, booking.currency)}</option>)}</select></label>
        <div className="grid gap-3 sm:grid-cols-2">
          <label className="text-sm font-medium">Amount<input aria-label="Payment amount" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="1250.00" className="mt-1 w-full rounded-md border border-border px-3 py-2" /></label>
          <label className="text-sm font-medium">Method<select aria-label="Payment method" value={method} onChange={(event) => setMethod(event.target.value as PaymentMethod)} className="mt-1 w-full rounded-md border border-border px-3 py-2">{paymentMethods.map((item) => <option key={item.value} value={item.value}>{methodLabel(item.value)}</option>)}</select></label>
          <label className="text-sm font-medium">Paid date<input aria-label="Paid date" type="date" value={paidAt} onChange={(event) => setPaidAt(event.target.value)} className="mt-1 w-full rounded-md border border-border px-3 py-2" /></label>
        </div>
        <label className="block text-sm font-medium">Notes<textarea aria-label="Payment notes" value={notes} onChange={(event) => setNotes(event.target.value)} className="mt-1 w-full rounded-md border border-border px-3 py-2" /></label>
        {localError || error ? <p role="alert" className="text-sm font-medium text-danger">{localError || error}</p> : null}
        <div className="flex justify-end gap-2"><button type="button" disabled={saving} onClick={onClose} className="rounded-md border border-border px-3 py-2 text-sm font-semibold disabled:opacity-50">Cancel</button><button type="submit" disabled={saving} className="rounded-md bg-primary px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">Create Payment</button></div>
      </form>
    </ConfirmDialog>
  );
}
