import { FormEvent, useState } from "react";
import { ConfirmDialog } from "../../components/common/ConfirmDialog";
import type { Bed, MaintenanceCategory, MaintenancePriority, Resident, Room } from "../../types/api";
import { bedLabel, categories, priorities, residentName, roomLabel } from "./maintenanceView";

export function CreateMaintenanceDialog({ open, residents, rooms, beds, saving, error, onClose, onCreate }: { open: boolean; residents: Resident[]; rooms: Room[]; beds: Bed[]; saving: boolean; error: string | null; onClose: () => void; onCreate: (input: { residentId?: number; roomId?: number; bedId?: number; category: MaintenanceCategory; priority?: MaintenancePriority; title: string; description?: string }) => void }) {
  const [residentId, setResidentId] = useState("");
  const [roomId, setRoomId] = useState("");
  const [bedId, setBedId] = useState("");
  const [category, setCategory] = useState<MaintenanceCategory>("plumbing");
  const [priority, setPriority] = useState<MaintenancePriority>("normal");
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const roomBeds = beds.filter((bed) => !roomId || bed.room_id === Number(roomId));
  function submit(event: FormEvent) {
    event.preventDefault();
    onCreate({
      residentId: residentId ? Number(residentId) : undefined,
      roomId: roomId ? Number(roomId) : undefined,
      bedId: bedId ? Number(bedId) : undefined,
      category,
      priority,
      title: title.trim(),
      description: description.trim() || undefined
    });
  }
  return (
    <ConfirmDialog open={open} title="Create maintenance request" description="Request numbers are generated by the backend. This does not change room or bed inventory status." onClose={onClose}>
      <form onSubmit={submit} className="space-y-4">
        <div className="grid gap-3 sm:grid-cols-2">
          <label className="text-sm font-medium">Resident<select aria-label="Maintenance resident" value={residentId} onChange={(event) => setResidentId(event.target.value)} className="mt-1 w-full rounded-md border border-border px-3 py-2"><option value="">No resident</option>{residents.map((resident) => <option key={resident.id} value={resident.id}>{resident.resident_code} - {residentName(resident)}</option>)}</select></label>
          <label className="text-sm font-medium">Room<select aria-label="Maintenance room" value={roomId} onChange={(event) => { setRoomId(event.target.value); setBedId(""); }} className="mt-1 w-full rounded-md border border-border px-3 py-2"><option value="">No room</option>{rooms.map((room) => <option key={room.id} value={room.id}>{roomLabel(room)}</option>)}</select></label>
          <label className="text-sm font-medium">Bed<select aria-label="Maintenance bed" value={bedId} onChange={(event) => setBedId(event.target.value)} className="mt-1 w-full rounded-md border border-border px-3 py-2"><option value="">No bed</option>{roomBeds.map((bed) => <option key={bed.id} value={bed.id}>{bedLabel(bed)}</option>)}</select></label>
          <label className="text-sm font-medium">Category<select aria-label="Maintenance category" value={category} onChange={(event) => setCategory(event.target.value as MaintenanceCategory)} className="mt-1 w-full rounded-md border border-border px-3 py-2">{categories.map((item) => <option key={item} value={item}>{item}</option>)}</select></label>
          <label className="text-sm font-medium">Priority<select aria-label="Maintenance priority" value={priority} onChange={(event) => setPriority(event.target.value as MaintenancePriority)} className="mt-1 w-full rounded-md border border-border px-3 py-2">{priorities.map((item) => <option key={item} value={item}>{item}</option>)}</select></label>
          <label className="text-sm font-medium">Issue<input aria-label="Maintenance issue" value={title} onChange={(event) => setTitle(event.target.value)} required className="mt-1 w-full rounded-md border border-border px-3 py-2" /></label>
        </div>
        <label className="block text-sm font-medium">Description<textarea aria-label="Maintenance description" value={description} onChange={(event) => setDescription(event.target.value)} className="mt-1 w-full rounded-md border border-border px-3 py-2" /></label>
        {error ? <p role="alert" className="text-sm font-medium text-danger">{error}</p> : null}
        <div className="flex justify-end gap-2"><button type="button" disabled={saving} onClick={onClose} className="rounded-md border border-border px-3 py-2 text-sm font-semibold disabled:opacity-50">Cancel</button><button type="submit" disabled={saving || !title.trim()} className="rounded-md bg-primary px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">Create Request</button></div>
      </form>
    </ConfirmDialog>
  );
}
