import { FormEvent, useMemo, useState } from "react";
import { ConfirmDialog } from "../../components/common/ConfirmDialog";
import type { AcademicSession, Application, AvailabilityBed, Institution, Resident } from "../../types/api";
import { formatCurrencyMinor } from "../../utils/format";

function residentName(resident?: Resident) {
  return resident ? [resident.first_name, resident.middle_name, resident.last_name].filter(Boolean).join(" ") : "Resident unavailable";
}

export function CreateBookingDialog({ open, applications, residentsById, institutions, sessions, availability, loadingAvailability, error, saving, onApplicationChange, onCreate, onClose }: { open: boolean; applications: Application[]; residentsById: Map<number, Resident>; institutions: Institution[]; sessions: AcademicSession[]; availability: AvailabilityBed[]; loadingAvailability: boolean; error: string | null; saving: boolean; onApplicationChange: (application: Application | null) => void; onCreate: (applicationId: number, roomId: number) => void; onClose: () => void }) {
  const [applicationId, setApplicationId] = useState("");
  const [roomId, setRoomId] = useState("");
  const selected = applications.find((application) => application.id === Number(applicationId));
  const resident = selected ? residentsById.get(selected.resident_id) : undefined;
  const session = selected ? sessions.find((item) => item.id === selected.academic_session_id) : undefined;
  const institution = resident?.institution_id ? institutions.find((item) => item.id === resident.institution_id) : undefined;
  const rooms = useMemo(() => {
    const map = new Map<number, AvailabilityBed>();
    availability.forEach((bed) => { if (!map.has(bed.room_id)) map.set(bed.room_id, bed); });
    return Array.from(map.values());
  }, [availability]);
  const selectedRoom = rooms.find((room) => room.room_id === Number(roomId));

  function changeApplication(value: string) {
    setApplicationId(value);
    setRoomId("");
    onApplicationChange(applications.find((application) => application.id === Number(value)) ?? null);
  }

  function submit(event: FormEvent) {
    event.preventDefault();
    if (selected && roomId) onCreate(selected.id, Number(roomId));
  }

  return (
    <ConfirmDialog open={open} title="Create Booking" description="Booking number and captured total are generated by the backend." onClose={onClose}>
      <form onSubmit={submit} className="space-y-4">
        <div>
          <label htmlFor="booking-application" className="block text-sm font-medium text-text-primary">Approved application</label>
          <select id="booking-application" value={applicationId} onChange={(event) => changeApplication(event.target.value)} className="mt-1 w-full rounded-md border border-border px-3 py-2 text-sm">
            <option value="">Select approved application</option>
            {applications.map((application) => <option key={application.id} value={application.id}>{application.application_number}</option>)}
          </select>
          {!applications.length ? <p className="mt-2 text-sm text-text-secondary">No approved applications are currently eligible for booking creation.</p> : null}
        </div>
        {selected ? (
          <section className="rounded border border-border p-3 text-sm">
            <p className="font-semibold">{residentName(resident)}</p>
            <p className="text-text-secondary">Student ID: {resident?.student_id ?? "Not set"} | Institution: {institution?.name ?? "Not set"} | Session: {session?.name ?? `Session #${selected.academic_session_id}`}</p>
          </section>
        ) : null}
        {selected ? (
          <div>
            <label htmlFor="booking-room" className="block text-sm font-medium text-text-primary">Eligible room with active rate</label>
            <select id="booking-room" value={roomId} onChange={(event) => setRoomId(event.target.value)} disabled={loadingAvailability} className="mt-1 w-full rounded-md border border-border px-3 py-2 text-sm">
              <option value="">{loadingAvailability ? "Loading availability..." : "Select room"}</option>
              {rooms.map((room) => <option key={room.room_id} value={room.room_id}>{room.room_code} - {formatCurrencyMinor(room.amount_minor, room.currency)}</option>)}
            </select>
            {!loadingAvailability && !rooms.length ? <p className="mt-2 text-sm text-danger">No eligible rooms with active rates are available for this application.</p> : null}
          </div>
        ) : null}
        {selectedRoom ? <p className="rounded border border-border bg-muted p-3 text-sm">Rate preview: {formatCurrencyMinor(selectedRoom.amount_minor, selectedRoom.currency)}. The backend response remains authoritative.</p> : null}
        {error ? <p role="alert" className="text-sm font-medium text-danger">{error}</p> : null}
        <div className="flex justify-end gap-2">
          <button type="button" onClick={onClose} disabled={saving} className="rounded-md border border-border px-3 py-2 text-sm font-semibold disabled:opacity-50">Cancel</button>
          <button type="submit" disabled={!selected || !roomId || saving} className="rounded-md bg-primary px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? "Creating..." : "Create Booking"}</button>
        </div>
      </form>
    </ConfirmDialog>
  );
}
